# Generated by Django 5.2.5 on 2025-08-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
